// Developer handoff packet (schema v1): the portable Markdown format both
// GradeVibes and FinalRead emit for a SUGGESTED fix to one audit finding.
// Shared between server, client, and tests so the packet contract has one
// definition. See docs/dev-handoff-packet-schema.md for the full spec.
//
// Design rules baked in here: the packet is review-only (nothing is applied),
// it carries a runtime disclaimer and a "not exhaustive" notice, and v1
// packets never contain effort estimates.

export interface DevHandoffFinding {
  title: string;
  message: string;
  severity: string;
  type: string;
  file: string;
  line: number | null;
  /** The scanner's own short recommendation, when one exists. */
  suggestion?: string;
}

export interface SuggestedFix {
  plainEnglishIssue: string;
  /** file:line reference plus the problem snippet, as the model wrote it. */
  evidence: string;
  /** Unified diff or labeled BEFORE/AFTER blocks showing the suggested change. */
  remediationDiff: string;
  verificationSteps: string[];
}

export interface DevHandoffPacketInput {
  /** "GradeVibes" or "FinalRead". */
  product: string;
  finding: DevHandoffFinding;
  fix: SuggestedFix;
  /** ISO 8601 timestamp. */
  generatedAt: string;
}

/** Strip one layer of markdown code fences so a diff can be safely embedded
 *  inside the packet's own fenced block. */
function unfence(text: string): string {
  const lines = String(text ?? "").split("\n");
  if (lines.length >= 2 && lines[0].trim().startsWith("```")) lines.shift();
  while (lines.length && lines[lines.length - 1].trim() === "```") lines.pop();
  if (lines.length && lines[lines.length - 1].trim().startsWith("```")) lines.pop();
  return lines.join("\n").trim();
}

function lineAnchor(file: string, line: number | null): string {
  return line != null ? `${file}:${line}` : file;
}

export function renderDevHandoffPacket(input: DevHandoffPacketInput): string {
  const { product, finding, fix, generatedAt } = input;
  const anchor = lineAnchor(finding.file, finding.line);
  const steps =
    fix.verificationSteps.length > 0
      ? fix.verificationSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")
      : "1. (No verification steps were provided — confirm the change manually before shipping.)";

  return [
    `# Developer handoff — suggested fix (REVIEW ONLY)`,
    ``,
    `**Product:** ${product}`,
    `**Generated:** ${generatedAt}`,
    `**Status:** Suggested fix — NOT applied. Human review required.`,
    ``,
    `## Finding`,
    ``,
    finding.title,
    ``,
    `## Source finding`,
    ``,
    `- **Message:** ${finding.message}`,
    `- **Severity:** ${finding.severity}`,
    `- **Type:** ${finding.type}`,
    ...(finding.suggestion ? [`- **Scanner recommendation:** ${finding.suggestion}`] : []),
    ``,
    `## Plain-English issue`,
    ``,
    fix.plainEnglishIssue,
    ``,
    `## Evidence`,
    ``,
    `\`${anchor}\``,
    ``,
    "```",
    unfence(fix.evidence),
    "```",
    ``,
    `## Suggested remediation`,
    ``,
    `The diff below is a suggestion only — it has not been applied to your code.`,
    ``,
    "```diff",
    unfence(fix.remediationDiff),
    "```",
    ``,
    `## How to verify the fix`,
    ``,
    steps,
    ``,
    `## Runtime disclaimer`,
    ``,
    `This suggestion was generated by an AI model from static analysis output. It was not executed, tested, or verified at runtime. Behavior in production may differ from what is described here.`,
    ``,
    `## Scope notice`,
    ``,
    `This packet is not exhaustive: it covers one finding only and does not certify the codebase. It is an automated suggestion — a human developer must review and approve any change before it ships.`,
    ``,
    `*No effort estimates are included in v1 packets by design.*`,
    ``,
  ].join("\n");
}
